version: '3'
services:
  app:
    image: your_image_name
    ports:
      - 3780:80
    volumes:
      - ./scraper:/app
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: scrapes
    expose:
      - "5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
      - postgres